// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/maklybae/plagiarism-checker/analysis/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateTextInfo provides a mock function for the type Repository
func (_mock *Repository) CreateTextInfo(ctx context.Context, text *domain.TextInfo) error {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for CreateTextInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TextInfo) error); ok {
		r0 = returnFunc(ctx, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_CreateTextInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTextInfo'
type Repository_CreateTextInfo_Call struct {
	*mock.Call
}

// CreateTextInfo is a helper method to define mock.On call
//   - ctx
//   - text
func (_e *Repository_Expecter) CreateTextInfo(ctx interface{}, text interface{}) *Repository_CreateTextInfo_Call {
	return &Repository_CreateTextInfo_Call{Call: _e.mock.On("CreateTextInfo", ctx, text)}
}

func (_c *Repository_CreateTextInfo_Call) Run(run func(ctx context.Context, text *domain.TextInfo)) *Repository_CreateTextInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.TextInfo))
	})
	return _c
}

func (_c *Repository_CreateTextInfo_Call) Return(err error) *Repository_CreateTextInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_CreateTextInfo_Call) RunAndReturn(run func(ctx context.Context, text *domain.TextInfo) error) *Repository_CreateTextInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTextInfoByID provides a mock function for the type Repository
func (_mock *Repository) GetTextInfoByID(ctx context.Context, id uuid.UUID) (*domain.TextInfo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTextInfoByID")
	}

	var r0 *domain.TextInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.TextInfo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.TextInfo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TextInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetTextInfoByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTextInfoByID'
type Repository_GetTextInfoByID_Call struct {
	*mock.Call
}

// GetTextInfoByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *Repository_Expecter) GetTextInfoByID(ctx interface{}, id interface{}) *Repository_GetTextInfoByID_Call {
	return &Repository_GetTextInfoByID_Call{Call: _e.mock.On("GetTextInfoByID", ctx, id)}
}

func (_c *Repository_GetTextInfoByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_GetTextInfoByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_GetTextInfoByID_Call) Return(textInfo *domain.TextInfo, err error) *Repository_GetTextInfoByID_Call {
	_c.Call.Return(textInfo, err)
	return _c
}

func (_c *Repository_GetTextInfoByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.TextInfo, error)) *Repository_GetTextInfoByID_Call {
	_c.Call.Return(run)
	return _c
}

// SetWordcloudPath provides a mock function for the type Repository
func (_mock *Repository) SetWordcloudPath(ctx context.Context, id uuid.UUID, path string) error {
	ret := _mock.Called(ctx, id, path)

	if len(ret) == 0 {
		panic("no return value specified for SetWordcloudPath")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_SetWordcloudPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWordcloudPath'
type Repository_SetWordcloudPath_Call struct {
	*mock.Call
}

// SetWordcloudPath is a helper method to define mock.On call
//   - ctx
//   - id
//   - path
func (_e *Repository_Expecter) SetWordcloudPath(ctx interface{}, id interface{}, path interface{}) *Repository_SetWordcloudPath_Call {
	return &Repository_SetWordcloudPath_Call{Call: _e.mock.On("SetWordcloudPath", ctx, id, path)}
}

func (_c *Repository_SetWordcloudPath_Call) Run(run func(ctx context.Context, id uuid.UUID, path string)) *Repository_SetWordcloudPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *Repository_SetWordcloudPath_Call) Return(err error) *Repository_SetWordcloudPath_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_SetWordcloudPath_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, path string) error) *Repository_SetWordcloudPath_Call {
	_c.Call.Return(run)
	return _c
}
