// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewWordcloudStorage creates a new instance of WordcloudStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWordcloudStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *WordcloudStorage {
	mock := &WordcloudStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WordcloudStorage is an autogenerated mock type for the WordcloudStorage type
type WordcloudStorage struct {
	mock.Mock
}

type WordcloudStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *WordcloudStorage) EXPECT() *WordcloudStorage_Expecter {
	return &WordcloudStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type WordcloudStorage
func (_mock *WordcloudStorage) Get(ctx context.Context, path string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WordcloudStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type WordcloudStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - path
func (_e *WordcloudStorage_Expecter) Get(ctx interface{}, path interface{}) *WordcloudStorage_Get_Call {
	return &WordcloudStorage_Get_Call{Call: _e.mock.On("Get", ctx, path)}
}

func (_c *WordcloudStorage_Get_Call) Run(run func(ctx context.Context, path string)) *WordcloudStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WordcloudStorage_Get_Call) Return(stream io.ReadCloser, err error) *WordcloudStorage_Get_Call {
	_c.Call.Return(stream, err)
	return _c
}

func (_c *WordcloudStorage_Get_Call) RunAndReturn(run func(ctx context.Context, path string) (io.ReadCloser, error)) *WordcloudStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type WordcloudStorage
func (_mock *WordcloudStorage) Save(ctx context.Context, path string) (io.WriteCloser, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 io.WriteCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.WriteCloser, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.WriteCloser); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WordcloudStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type WordcloudStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx
//   - path
func (_e *WordcloudStorage_Expecter) Save(ctx interface{}, path interface{}) *WordcloudStorage_Save_Call {
	return &WordcloudStorage_Save_Call{Call: _e.mock.On("Save", ctx, path)}
}

func (_c *WordcloudStorage_Save_Call) Run(run func(ctx context.Context, path string)) *WordcloudStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WordcloudStorage_Save_Call) Return(stream io.WriteCloser, err error) *WordcloudStorage_Save_Call {
	_c.Call.Return(stream, err)
	return _c
}

func (_c *WordcloudStorage_Save_Call) RunAndReturn(run func(ctx context.Context, path string) (io.WriteCloser, error)) *WordcloudStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}
