// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package types

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	// Code HTTP status code
	Code *int `json:"code,omitempty"`

	// Message Error message
	Message *string `json:"message,omitempty"`
}

// PostApiV1AnalysisDiffJSONBody defines parameters for PostApiV1AnalysisDiff.
type PostApiV1AnalysisDiffJSONBody struct {
	FileIdA openapi_types.UUID `json:"file_id_a"`
	FileIdB openapi_types.UUID `json:"file_id_b"`
}

// PostApiV1AnalysisSingleJSONBody defines parameters for PostApiV1AnalysisSingle.
type PostApiV1AnalysisSingleJSONBody struct {
	// FileId File UUID
	FileId openapi_types.UUID `json:"file_id"`
}

// PostApiV1AnalysisWordcloudJSONBody defines parameters for PostApiV1AnalysisWordcloud.
type PostApiV1AnalysisWordcloudJSONBody struct {
	FileId openapi_types.UUID `json:"file_id"`
}

// GetApiV1StorageParams defines parameters for GetApiV1Storage.
type GetApiV1StorageParams struct {
	FileId openapi_types.UUID `form:"file_id" json:"file_id"`
}

// PostApiV1AnalysisDiffJSONRequestBody defines body for PostApiV1AnalysisDiff for application/json ContentType.
type PostApiV1AnalysisDiffJSONRequestBody PostApiV1AnalysisDiffJSONBody

// PostApiV1AnalysisSingleJSONRequestBody defines body for PostApiV1AnalysisSingle for application/json ContentType.
type PostApiV1AnalysisSingleJSONRequestBody PostApiV1AnalysisSingleJSONBody

// PostApiV1AnalysisWordcloudJSONRequestBody defines body for PostApiV1AnalysisWordcloud for application/json ContentType.
type PostApiV1AnalysisWordcloudJSONRequestBody PostApiV1AnalysisWordcloudJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Compare two files
	// (POST /api/v1/analysis/diff)
	PostApiV1AnalysisDiff(c *gin.Context)
	// Analyze a single file
	// (POST /api/v1/analysis/single)
	PostApiV1AnalysisSingle(c *gin.Context)
	// Generate wordcloud for a file
	// (POST /api/v1/analysis/wordcloud)
	PostApiV1AnalysisWordcloud(c *gin.Context)
	// Download a file
	// (GET /api/v1/storage)
	GetApiV1Storage(c *gin.Context, params GetApiV1StorageParams)
	// Upload a file
	// (POST /api/v1/storage)
	PostApiV1Storage(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostApiV1AnalysisDiff operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AnalysisDiff(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1AnalysisDiff(c)
}

// PostApiV1AnalysisSingle operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AnalysisSingle(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1AnalysisSingle(c)
}

// PostApiV1AnalysisWordcloud operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AnalysisWordcloud(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1AnalysisWordcloud(c)
}

// GetApiV1Storage operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Storage(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1StorageParams

	// ------------- Required query parameter "file_id" -------------

	if paramValue := c.Query("file_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument file_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "file_id", c.Request.URL.Query(), &params.FileId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter file_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1Storage(c, params)
}

// PostApiV1Storage operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Storage(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Storage(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/analysis/diff", wrapper.PostApiV1AnalysisDiff)
	router.POST(options.BaseURL+"/api/v1/analysis/single", wrapper.PostApiV1AnalysisSingle)
	router.POST(options.BaseURL+"/api/v1/analysis/wordcloud", wrapper.PostApiV1AnalysisWordcloud)
	router.GET(options.BaseURL+"/api/v1/storage", wrapper.GetApiV1Storage)
	router.POST(options.BaseURL+"/api/v1/storage", wrapper.PostApiV1Storage)
}
