// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: analysis/analysis.proto

package analysis

import (
	common "github.com/maklybae/plagiarism-checker/genproto/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileStatistics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalLines      uint64                 `protobuf:"varint,1,opt,name=total_lines,json=totalLines,proto3" json:"total_lines,omitempty"`
	TotalWords      uint64                 `protobuf:"varint,2,opt,name=total_words,json=totalWords,proto3" json:"total_words,omitempty"`
	TotalCharacters uint64                 `protobuf:"varint,3,opt,name=total_characters,json=totalCharacters,proto3" json:"total_characters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileStatistics) Reset() {
	*x = FileStatistics{}
	mi := &file_analysis_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatistics) ProtoMessage() {}

func (x *FileStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatistics.ProtoReflect.Descriptor instead.
func (*FileStatistics) Descriptor() ([]byte, []int) {
	return file_analysis_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *FileStatistics) GetTotalLines() uint64 {
	if x != nil {
		return x.TotalLines
	}
	return 0
}

func (x *FileStatistics) GetTotalWords() uint64 {
	if x != nil {
		return x.TotalWords
	}
	return 0
}

func (x *FileStatistics) GetTotalCharacters() uint64 {
	if x != nil {
		return x.TotalCharacters
	}
	return 0
}

type SingleFileAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        *common.UUID           `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleFileAnalysisRequest) Reset() {
	*x = SingleFileAnalysisRequest{}
	mi := &file_analysis_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleFileAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleFileAnalysisRequest) ProtoMessage() {}

func (x *SingleFileAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleFileAnalysisRequest.ProtoReflect.Descriptor instead.
func (*SingleFileAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_analysis_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *SingleFileAnalysisRequest) GetFileId() *common.UUID {
	if x != nil {
		return x.FileId
	}
	return nil
}

type SingleFileAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        *common.UUID           `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Statistics    *FileStatistics        `protobuf:"bytes,2,opt,name=statistics,proto3" json:"statistics,omitempty"`
	ExactMatches  []*common.UUID         `protobuf:"bytes,3,rep,name=exact_matches,json=exactMatches,proto3" json:"exact_matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleFileAnalysisResponse) Reset() {
	*x = SingleFileAnalysisResponse{}
	mi := &file_analysis_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleFileAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleFileAnalysisResponse) ProtoMessage() {}

func (x *SingleFileAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleFileAnalysisResponse.ProtoReflect.Descriptor instead.
func (*SingleFileAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_analysis_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *SingleFileAnalysisResponse) GetFileId() *common.UUID {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *SingleFileAnalysisResponse) GetStatistics() *FileStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *SingleFileAnalysisResponse) GetExactMatches() []*common.UUID {
	if x != nil {
		return x.ExactMatches
	}
	return nil
}

type DiffFileAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileIdA       *common.UUID           `protobuf:"bytes,1,opt,name=file_id_a,json=fileIdA,proto3" json:"file_id_a,omitempty"`
	FileIdB       *common.UUID           `protobuf:"bytes,2,opt,name=file_id_b,json=fileIdB,proto3" json:"file_id_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffFileAnalysisRequest) Reset() {
	*x = DiffFileAnalysisRequest{}
	mi := &file_analysis_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffFileAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffFileAnalysisRequest) ProtoMessage() {}

func (x *DiffFileAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffFileAnalysisRequest.ProtoReflect.Descriptor instead.
func (*DiffFileAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_analysis_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *DiffFileAnalysisRequest) GetFileIdA() *common.UUID {
	if x != nil {
		return x.FileIdA
	}
	return nil
}

func (x *DiffFileAnalysisRequest) GetFileIdB() *common.UUID {
	if x != nil {
		return x.FileIdB
	}
	return nil
}

type DiffFileAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileIdA       *common.UUID           `protobuf:"bytes,1,opt,name=file_id_a,json=fileIdA,proto3" json:"file_id_a,omitempty"`
	FileIdB       *common.UUID           `protobuf:"bytes,2,opt,name=file_id_b,json=fileIdB,proto3" json:"file_id_b,omitempty"`
	Similarity    float64                `protobuf:"fixed64,3,opt,name=similarity,proto3" json:"similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffFileAnalysisResponse) Reset() {
	*x = DiffFileAnalysisResponse{}
	mi := &file_analysis_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffFileAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffFileAnalysisResponse) ProtoMessage() {}

func (x *DiffFileAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffFileAnalysisResponse.ProtoReflect.Descriptor instead.
func (*DiffFileAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_analysis_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *DiffFileAnalysisResponse) GetFileIdA() *common.UUID {
	if x != nil {
		return x.FileIdA
	}
	return nil
}

func (x *DiffFileAnalysisResponse) GetFileIdB() *common.UUID {
	if x != nil {
		return x.FileIdB
	}
	return nil
}

func (x *DiffFileAnalysisResponse) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

type WordCloudRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        *common.UUID           `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordCloudRequest) Reset() {
	*x = WordCloudRequest{}
	mi := &file_analysis_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordCloudRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCloudRequest) ProtoMessage() {}

func (x *WordCloudRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCloudRequest.ProtoReflect.Descriptor instead.
func (*WordCloudRequest) Descriptor() ([]byte, []int) {
	return file_analysis_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *WordCloudRequest) GetFileId() *common.UUID {
	if x != nil {
		return x.FileId
	}
	return nil
}

type WordCloudResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *common.FileChunk      `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordCloudResponse) Reset() {
	*x = WordCloudResponse{}
	mi := &file_analysis_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordCloudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCloudResponse) ProtoMessage() {}

func (x *WordCloudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCloudResponse.ProtoReflect.Descriptor instead.
func (*WordCloudResponse) Descriptor() ([]byte, []int) {
	return file_analysis_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *WordCloudResponse) GetFile() *common.FileChunk {
	if x != nil {
		return x.File
	}
	return nil
}

var File_analysis_analysis_proto protoreflect.FileDescriptor

const file_analysis_analysis_proto_rawDesc = "" +
	"\n" +
	"\x17analysis/analysis.proto\x12\banalysis\x1a\x13common/common.proto\"}\n" +
	"\x0eFileStatistics\x12\x1f\n" +
	"\vtotal_lines\x18\x01 \x01(\x04R\n" +
	"totalLines\x12\x1f\n" +
	"\vtotal_words\x18\x02 \x01(\x04R\n" +
	"totalWords\x12)\n" +
	"\x10total_characters\x18\x03 \x01(\x04R\x0ftotalCharacters\"B\n" +
	"\x19SingleFileAnalysisRequest\x12%\n" +
	"\afile_id\x18\x01 \x01(\v2\f.common.UUIDR\x06fileId\"\xb0\x01\n" +
	"\x1aSingleFileAnalysisResponse\x12%\n" +
	"\afile_id\x18\x01 \x01(\v2\f.common.UUIDR\x06fileId\x128\n" +
	"\n" +
	"statistics\x18\x02 \x01(\v2\x18.analysis.FileStatisticsR\n" +
	"statistics\x121\n" +
	"\rexact_matches\x18\x03 \x03(\v2\f.common.UUIDR\fexactMatches\"m\n" +
	"\x17DiffFileAnalysisRequest\x12(\n" +
	"\tfile_id_a\x18\x01 \x01(\v2\f.common.UUIDR\afileIdA\x12(\n" +
	"\tfile_id_b\x18\x02 \x01(\v2\f.common.UUIDR\afileIdB\"\x8e\x01\n" +
	"\x18DiffFileAnalysisResponse\x12(\n" +
	"\tfile_id_a\x18\x01 \x01(\v2\f.common.UUIDR\afileIdA\x12(\n" +
	"\tfile_id_b\x18\x02 \x01(\v2\f.common.UUIDR\afileIdB\x12\x1e\n" +
	"\n" +
	"similarity\x18\x03 \x01(\x01R\n" +
	"similarity\"9\n" +
	"\x10WordCloudRequest\x12%\n" +
	"\afile_id\x18\x01 \x01(\v2\f.common.UUIDR\x06fileId\":\n" +
	"\x11WordCloudResponse\x12%\n" +
	"\x04file\x18\x02 \x01(\v2\x11.common.FileChunkR\x04file2\x93\x02\n" +
	"\x0fAnalysisService\x12_\n" +
	"\x12SingleFileAnalysis\x12#.analysis.SingleFileAnalysisRequest\x1a$.analysis.SingleFileAnalysisResponse\x12Y\n" +
	"\x10DiffFileAnalysis\x12!.analysis.DiffFileAnalysisRequest\x1a\".analysis.DiffFileAnalysisResponse\x12D\n" +
	"\tWordCloud\x12\x1a.analysis.WordCloudRequest\x1a\x1b.analysis.WordCloudResponseB=Z;github.com/maklybae/plagiarism-checker/genproto/go/analysisb\x06proto3"

var (
	file_analysis_analysis_proto_rawDescOnce sync.Once
	file_analysis_analysis_proto_rawDescData []byte
)

func file_analysis_analysis_proto_rawDescGZIP() []byte {
	file_analysis_analysis_proto_rawDescOnce.Do(func() {
		file_analysis_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analysis_analysis_proto_rawDesc), len(file_analysis_analysis_proto_rawDesc)))
	})
	return file_analysis_analysis_proto_rawDescData
}

var file_analysis_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_analysis_analysis_proto_goTypes = []any{
	(*FileStatistics)(nil),             // 0: analysis.FileStatistics
	(*SingleFileAnalysisRequest)(nil),  // 1: analysis.SingleFileAnalysisRequest
	(*SingleFileAnalysisResponse)(nil), // 2: analysis.SingleFileAnalysisResponse
	(*DiffFileAnalysisRequest)(nil),    // 3: analysis.DiffFileAnalysisRequest
	(*DiffFileAnalysisResponse)(nil),   // 4: analysis.DiffFileAnalysisResponse
	(*WordCloudRequest)(nil),           // 5: analysis.WordCloudRequest
	(*WordCloudResponse)(nil),          // 6: analysis.WordCloudResponse
	(*common.UUID)(nil),                // 7: common.UUID
	(*common.FileChunk)(nil),           // 8: common.FileChunk
}
var file_analysis_analysis_proto_depIdxs = []int32{
	7,  // 0: analysis.SingleFileAnalysisRequest.file_id:type_name -> common.UUID
	7,  // 1: analysis.SingleFileAnalysisResponse.file_id:type_name -> common.UUID
	0,  // 2: analysis.SingleFileAnalysisResponse.statistics:type_name -> analysis.FileStatistics
	7,  // 3: analysis.SingleFileAnalysisResponse.exact_matches:type_name -> common.UUID
	7,  // 4: analysis.DiffFileAnalysisRequest.file_id_a:type_name -> common.UUID
	7,  // 5: analysis.DiffFileAnalysisRequest.file_id_b:type_name -> common.UUID
	7,  // 6: analysis.DiffFileAnalysisResponse.file_id_a:type_name -> common.UUID
	7,  // 7: analysis.DiffFileAnalysisResponse.file_id_b:type_name -> common.UUID
	7,  // 8: analysis.WordCloudRequest.file_id:type_name -> common.UUID
	8,  // 9: analysis.WordCloudResponse.file:type_name -> common.FileChunk
	1,  // 10: analysis.AnalysisService.SingleFileAnalysis:input_type -> analysis.SingleFileAnalysisRequest
	3,  // 11: analysis.AnalysisService.DiffFileAnalysis:input_type -> analysis.DiffFileAnalysisRequest
	5,  // 12: analysis.AnalysisService.WordCloud:input_type -> analysis.WordCloudRequest
	2,  // 13: analysis.AnalysisService.SingleFileAnalysis:output_type -> analysis.SingleFileAnalysisResponse
	4,  // 14: analysis.AnalysisService.DiffFileAnalysis:output_type -> analysis.DiffFileAnalysisResponse
	6,  // 15: analysis.AnalysisService.WordCloud:output_type -> analysis.WordCloudResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_analysis_analysis_proto_init() }
func file_analysis_analysis_proto_init() {
	if File_analysis_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analysis_analysis_proto_rawDesc), len(file_analysis_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analysis_analysis_proto_goTypes,
		DependencyIndexes: file_analysis_analysis_proto_depIdxs,
		MessageInfos:      file_analysis_analysis_proto_msgTypes,
	}.Build()
	File_analysis_analysis_proto = out.File
	file_analysis_analysis_proto_goTypes = nil
	file_analysis_analysis_proto_depIdxs = nil
}
