// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: analysis/analysis.proto

package analysis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalysisService_SingleFileAnalysis_FullMethodName = "/analysis.AnalysisService/SingleFileAnalysis"
	AnalysisService_DiffFileAnalysis_FullMethodName   = "/analysis.AnalysisService/DiffFileAnalysis"
	AnalysisService_WordCloud_FullMethodName          = "/analysis.AnalysisService/WordCloud"
)

// AnalysisServiceClient is the client API for AnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalysisServiceClient interface {
	SingleFileAnalysis(ctx context.Context, in *SingleFileAnalysisRequest, opts ...grpc.CallOption) (*SingleFileAnalysisResponse, error)
	DiffFileAnalysis(ctx context.Context, in *DiffFileAnalysisRequest, opts ...grpc.CallOption) (*DiffFileAnalysisResponse, error)
	WordCloud(ctx context.Context, in *WordCloudRequest, opts ...grpc.CallOption) (*WordCloudResponse, error)
}

type analysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalysisServiceClient(cc grpc.ClientConnInterface) AnalysisServiceClient {
	return &analysisServiceClient{cc}
}

func (c *analysisServiceClient) SingleFileAnalysis(ctx context.Context, in *SingleFileAnalysisRequest, opts ...grpc.CallOption) (*SingleFileAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleFileAnalysisResponse)
	err := c.cc.Invoke(ctx, AnalysisService_SingleFileAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) DiffFileAnalysis(ctx context.Context, in *DiffFileAnalysisRequest, opts ...grpc.CallOption) (*DiffFileAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffFileAnalysisResponse)
	err := c.cc.Invoke(ctx, AnalysisService_DiffFileAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) WordCloud(ctx context.Context, in *WordCloudRequest, opts ...grpc.CallOption) (*WordCloudResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WordCloudResponse)
	err := c.cc.Invoke(ctx, AnalysisService_WordCloud_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisServiceServer is the server API for AnalysisService service.
// All implementations must embed UnimplementedAnalysisServiceServer
// for forward compatibility.
type AnalysisServiceServer interface {
	SingleFileAnalysis(context.Context, *SingleFileAnalysisRequest) (*SingleFileAnalysisResponse, error)
	DiffFileAnalysis(context.Context, *DiffFileAnalysisRequest) (*DiffFileAnalysisResponse, error)
	WordCloud(context.Context, *WordCloudRequest) (*WordCloudResponse, error)
	mustEmbedUnimplementedAnalysisServiceServer()
}

// UnimplementedAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalysisServiceServer struct{}

func (UnimplementedAnalysisServiceServer) SingleFileAnalysis(context.Context, *SingleFileAnalysisRequest) (*SingleFileAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SingleFileAnalysis not implemented")
}
func (UnimplementedAnalysisServiceServer) DiffFileAnalysis(context.Context, *DiffFileAnalysisRequest) (*DiffFileAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiffFileAnalysis not implemented")
}
func (UnimplementedAnalysisServiceServer) WordCloud(context.Context, *WordCloudRequest) (*WordCloudResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WordCloud not implemented")
}
func (UnimplementedAnalysisServiceServer) mustEmbedUnimplementedAnalysisServiceServer() {}
func (UnimplementedAnalysisServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalysisServiceServer will
// result in compilation errors.
type UnsafeAnalysisServiceServer interface {
	mustEmbedUnimplementedAnalysisServiceServer()
}

func RegisterAnalysisServiceServer(s grpc.ServiceRegistrar, srv AnalysisServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalysisService_ServiceDesc, srv)
}

func _AnalysisService_SingleFileAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleFileAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).SingleFileAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_SingleFileAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).SingleFileAnalysis(ctx, req.(*SingleFileAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_DiffFileAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffFileAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).DiffFileAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_DiffFileAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).DiffFileAnalysis(ctx, req.(*DiffFileAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_WordCloud_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordCloudRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).WordCloud(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_WordCloud_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).WordCloud(ctx, req.(*WordCloudRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalysisService_ServiceDesc is the grpc.ServiceDesc for AnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analysis.AnalysisService",
	HandlerType: (*AnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SingleFileAnalysis",
			Handler:    _AnalysisService_SingleFileAnalysis_Handler,
		},
		{
			MethodName: "DiffFileAnalysis",
			Handler:    _AnalysisService_DiffFileAnalysis_Handler,
		},
		{
			MethodName: "WordCloud",
			Handler:    _AnalysisService_WordCloud_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analysis/analysis.proto",
}
