// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: storage/storage.proto

package storage

import (
	common "github.com/maklybae/plagiarism-checker/genproto/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *common.FileChunk      `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetFile() *common.FileChunk {
	if x != nil {
		return x.File
	}
	return nil
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        *common.UUID           `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResponse) GetFileId() *common.UUID {
	if x != nil {
		return x.FileId
	}
	return nil
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        *common.UUID           `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadFileRequest) GetFileId() *common.UUID {
	if x != nil {
		return x.FileId
	}
	return nil
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *common.FileChunk      `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadFileResponse) GetFile() *common.FileChunk {
	if x != nil {
		return x.File
	}
	return nil
}

var File_storage_storage_proto protoreflect.FileDescriptor

const file_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x15storage/storage.proto\x12\astorage\x1a\x13common/common.proto\":\n" +
	"\x11UploadFileRequest\x12%\n" +
	"\x04file\x18\x01 \x01(\v2\x11.common.FileChunkR\x04file\";\n" +
	"\x12UploadFileResponse\x12%\n" +
	"\afile_id\x18\x01 \x01(\v2\f.common.UUIDR\x06fileId\"<\n" +
	"\x13DownloadFileRequest\x12%\n" +
	"\afile_id\x18\x01 \x01(\v2\f.common.UUIDR\x06fileId\"=\n" +
	"\x14DownloadFileResponse\x12%\n" +
	"\x04file\x18\x02 \x01(\v2\x11.common.FileChunkR\x04file2\xa8\x01\n" +
	"\x0eStorageService\x12G\n" +
	"\n" +
	"UploadFile\x12\x1a.storage.UploadFileRequest\x1a\x1b.storage.UploadFileResponse(\x01\x12M\n" +
	"\fDownloadFile\x12\x1c.storage.DownloadFileRequest\x1a\x1d.storage.DownloadFileResponse0\x01B<Z:github.com/maklybae/plagiarism-checker/genproto/go/storageb\x06proto3"

var (
	file_storage_storage_proto_rawDescOnce sync.Once
	file_storage_storage_proto_rawDescData []byte
)

func file_storage_storage_proto_rawDescGZIP() []byte {
	file_storage_storage_proto_rawDescOnce.Do(func() {
		file_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_storage_proto_rawDesc), len(file_storage_storage_proto_rawDesc)))
	})
	return file_storage_storage_proto_rawDescData
}

var file_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storage_storage_proto_goTypes = []any{
	(*UploadFileRequest)(nil),    // 0: storage.UploadFileRequest
	(*UploadFileResponse)(nil),   // 1: storage.UploadFileResponse
	(*DownloadFileRequest)(nil),  // 2: storage.DownloadFileRequest
	(*DownloadFileResponse)(nil), // 3: storage.DownloadFileResponse
	(*common.FileChunk)(nil),     // 4: common.FileChunk
	(*common.UUID)(nil),          // 5: common.UUID
}
var file_storage_storage_proto_depIdxs = []int32{
	4, // 0: storage.UploadFileRequest.file:type_name -> common.FileChunk
	5, // 1: storage.UploadFileResponse.file_id:type_name -> common.UUID
	5, // 2: storage.DownloadFileRequest.file_id:type_name -> common.UUID
	4, // 3: storage.DownloadFileResponse.file:type_name -> common.FileChunk
	0, // 4: storage.StorageService.UploadFile:input_type -> storage.UploadFileRequest
	2, // 5: storage.StorageService.DownloadFile:input_type -> storage.DownloadFileRequest
	1, // 6: storage.StorageService.UploadFile:output_type -> storage.UploadFileResponse
	3, // 7: storage.StorageService.DownloadFile:output_type -> storage.DownloadFileResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_storage_storage_proto_init() }
func file_storage_storage_proto_init() {
	if File_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_storage_proto_rawDesc), len(file_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_storage_proto_goTypes,
		DependencyIndexes: file_storage_storage_proto_depIdxs,
		MessageInfos:      file_storage_storage_proto_msgTypes,
	}.Build()
	File_storage_storage_proto = out.File
	file_storage_storage_proto_goTypes = nil
	file_storage_storage_proto_depIdxs = nil
}
