// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewWordcloudClient creates a new instance of WordcloudClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWordcloudClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *WordcloudClient {
	mock := &WordcloudClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WordcloudClient is an autogenerated mock type for the WordcloudClient type
type WordcloudClient struct {
	mock.Mock
}

type WordcloudClient_Expecter struct {
	mock *mock.Mock
}

func (_m *WordcloudClient) EXPECT() *WordcloudClient_Expecter {
	return &WordcloudClient_Expecter{mock: &_m.Mock}
}

// GetImage provides a mock function for the type WordcloudClient
func (_mock *WordcloudClient) GetImage(ctx context.Context, text string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for GetImage")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WordcloudClient_GetImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImage'
type WordcloudClient_GetImage_Call struct {
	*mock.Call
}

// GetImage is a helper method to define mock.On call
//   - ctx
//   - text
func (_e *WordcloudClient_Expecter) GetImage(ctx interface{}, text interface{}) *WordcloudClient_GetImage_Call {
	return &WordcloudClient_GetImage_Call{Call: _e.mock.On("GetImage", ctx, text)}
}

func (_c *WordcloudClient_GetImage_Call) Run(run func(ctx context.Context, text string)) *WordcloudClient_GetImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WordcloudClient_GetImage_Call) Return(reader io.ReadCloser, err error) *WordcloudClient_GetImage_Call {
	_c.Call.Return(reader, err)
	return _c
}

func (_c *WordcloudClient_GetImage_Call) RunAndReturn(run func(ctx context.Context, text string) (io.ReadCloser, error)) *WordcloudClient_GetImage_Call {
	_c.Call.Return(run)
	return _c
}
