// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/maklybae/plagiarism-checker/storage/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateFile provides a mock function for the type Repository
func (_mock *Repository) CreateFile(ctx context.Context, file *domain.FileInfo) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.FileInfo) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_CreateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFile'
type Repository_CreateFile_Call struct {
	*mock.Call
}

// CreateFile is a helper method to define mock.On call
//   - ctx
//   - file
func (_e *Repository_Expecter) CreateFile(ctx interface{}, file interface{}) *Repository_CreateFile_Call {
	return &Repository_CreateFile_Call{Call: _e.mock.On("CreateFile", ctx, file)}
}

func (_c *Repository_CreateFile_Call) Run(run func(ctx context.Context, file *domain.FileInfo)) *Repository_CreateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.FileInfo))
	})
	return _c
}

func (_c *Repository_CreateFile_Call) Return(err error) *Repository_CreateFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_CreateFile_Call) RunAndReturn(run func(ctx context.Context, file *domain.FileInfo) error) *Repository_CreateFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByID provides a mock function for the type Repository
func (_mock *Repository) GetFileByID(ctx context.Context, id uuid.UUID) (*domain.FileInfo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByID")
	}

	var r0 *domain.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.FileInfo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.FileInfo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetFileByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByID'
type Repository_GetFileByID_Call struct {
	*mock.Call
}

// GetFileByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *Repository_Expecter) GetFileByID(ctx interface{}, id interface{}) *Repository_GetFileByID_Call {
	return &Repository_GetFileByID_Call{Call: _e.mock.On("GetFileByID", ctx, id)}
}

func (_c *Repository_GetFileByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_GetFileByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_GetFileByID_Call) Return(file *domain.FileInfo, err error) *Repository_GetFileByID_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *Repository_GetFileByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.FileInfo, error)) *Repository_GetFileByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByHash provides a mock function for the type Repository
func (_mock *Repository) GetFilesByHash(ctx context.Context, hash string) ([]*domain.FileInfo, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByHash")
	}

	var r0 []*domain.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*domain.FileInfo, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*domain.FileInfo); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetFilesByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByHash'
type Repository_GetFilesByHash_Call struct {
	*mock.Call
}

// GetFilesByHash is a helper method to define mock.On call
//   - ctx
//   - hash
func (_e *Repository_Expecter) GetFilesByHash(ctx interface{}, hash interface{}) *Repository_GetFilesByHash_Call {
	return &Repository_GetFilesByHash_Call{Call: _e.mock.On("GetFilesByHash", ctx, hash)}
}

func (_c *Repository_GetFilesByHash_Call) Run(run func(ctx context.Context, hash string)) *Repository_GetFilesByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_GetFilesByHash_Call) Return(fileInfos []*domain.FileInfo, err error) *Repository_GetFilesByHash_Call {
	_c.Call.Return(fileInfos, err)
	return _c
}

func (_c *Repository_GetFilesByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) ([]*domain.FileInfo, error)) *Repository_GetFilesByHash_Call {
	_c.Call.Return(run)
	return _c
}
