// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/maklybae/plagiarism-checker/genproto/go/storage"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewStorageServiceClient creates a new instance of StorageServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageServiceClient {
	mock := &StorageServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StorageServiceClient is an autogenerated mock type for the StorageServiceClient type
type StorageServiceClient struct {
	mock.Mock
}

type StorageServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageServiceClient) EXPECT() *StorageServiceClient_Expecter {
	return &StorageServiceClient_Expecter{mock: &_m.Mock}
}

// DownloadFile provides a mock function for the type StorageServiceClient
func (_mock *StorageServiceClient) DownloadFile(ctx context.Context, in *storage.DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[storage.DownloadFileResponse], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 grpc.ServerStreamingClient[storage.DownloadFileResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.DownloadFileRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[storage.DownloadFileResponse], error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.DownloadFileRequest, ...grpc.CallOption) grpc.ServerStreamingClient[storage.DownloadFileResponse]); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[storage.DownloadFileResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *storage.DownloadFileRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StorageServiceClient_DownloadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFile'
type StorageServiceClient_DownloadFile_Call struct {
	*mock.Call
}

// DownloadFile is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *StorageServiceClient_Expecter) DownloadFile(ctx interface{}, in interface{}, opts ...interface{}) *StorageServiceClient_DownloadFile_Call {
	return &StorageServiceClient_DownloadFile_Call{Call: _e.mock.On("DownloadFile",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *StorageServiceClient_DownloadFile_Call) Run(run func(ctx context.Context, in *storage.DownloadFileRequest, opts ...grpc.CallOption)) *StorageServiceClient_DownloadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*storage.DownloadFileRequest), variadicArgs...)
	})
	return _c
}

func (_c *StorageServiceClient_DownloadFile_Call) Return(serverStreamingClient grpc.ServerStreamingClient[storage.DownloadFileResponse], err error) *StorageServiceClient_DownloadFile_Call {
	_c.Call.Return(serverStreamingClient, err)
	return _c
}

func (_c *StorageServiceClient_DownloadFile_Call) RunAndReturn(run func(ctx context.Context, in *storage.DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[storage.DownloadFileResponse], error)) *StorageServiceClient_DownloadFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileHash provides a mock function for the type StorageServiceClient
func (_mock *StorageServiceClient) GetFileHash(ctx context.Context, in *storage.GetFileHashRequest, opts ...grpc.CallOption) (*storage.GetFileHashResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetFileHash")
	}

	var r0 *storage.GetFileHashResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.GetFileHashRequest, ...grpc.CallOption) (*storage.GetFileHashResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.GetFileHashRequest, ...grpc.CallOption) *storage.GetFileHashResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.GetFileHashResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *storage.GetFileHashRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StorageServiceClient_GetFileHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileHash'
type StorageServiceClient_GetFileHash_Call struct {
	*mock.Call
}

// GetFileHash is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *StorageServiceClient_Expecter) GetFileHash(ctx interface{}, in interface{}, opts ...interface{}) *StorageServiceClient_GetFileHash_Call {
	return &StorageServiceClient_GetFileHash_Call{Call: _e.mock.On("GetFileHash",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *StorageServiceClient_GetFileHash_Call) Run(run func(ctx context.Context, in *storage.GetFileHashRequest, opts ...grpc.CallOption)) *StorageServiceClient_GetFileHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*storage.GetFileHashRequest), variadicArgs...)
	})
	return _c
}

func (_c *StorageServiceClient_GetFileHash_Call) Return(getFileHashResponse *storage.GetFileHashResponse, err error) *StorageServiceClient_GetFileHash_Call {
	_c.Call.Return(getFileHashResponse, err)
	return _c
}

func (_c *StorageServiceClient_GetFileHash_Call) RunAndReturn(run func(ctx context.Context, in *storage.GetFileHashRequest, opts ...grpc.CallOption) (*storage.GetFileHashResponse, error)) *StorageServiceClient_GetFileHash_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesByHash provides a mock function for the type StorageServiceClient
func (_mock *StorageServiceClient) ListFilesByHash(ctx context.Context, in *storage.ListFilesByHashRequest, opts ...grpc.CallOption) (*storage.ListFilesByHashResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListFilesByHash")
	}

	var r0 *storage.ListFilesByHashResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListFilesByHashRequest, ...grpc.CallOption) (*storage.ListFilesByHashResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListFilesByHashRequest, ...grpc.CallOption) *storage.ListFilesByHashResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ListFilesByHashResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *storage.ListFilesByHashRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StorageServiceClient_ListFilesByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesByHash'
type StorageServiceClient_ListFilesByHash_Call struct {
	*mock.Call
}

// ListFilesByHash is a helper method to define mock.On call
//   - ctx
//   - in
//   - opts
func (_e *StorageServiceClient_Expecter) ListFilesByHash(ctx interface{}, in interface{}, opts ...interface{}) *StorageServiceClient_ListFilesByHash_Call {
	return &StorageServiceClient_ListFilesByHash_Call{Call: _e.mock.On("ListFilesByHash",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *StorageServiceClient_ListFilesByHash_Call) Run(run func(ctx context.Context, in *storage.ListFilesByHashRequest, opts ...grpc.CallOption)) *StorageServiceClient_ListFilesByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]grpc.CallOption)
		run(args[0].(context.Context), args[1].(*storage.ListFilesByHashRequest), variadicArgs...)
	})
	return _c
}

func (_c *StorageServiceClient_ListFilesByHash_Call) Return(listFilesByHashResponse *storage.ListFilesByHashResponse, err error) *StorageServiceClient_ListFilesByHash_Call {
	_c.Call.Return(listFilesByHashResponse, err)
	return _c
}

func (_c *StorageServiceClient_ListFilesByHash_Call) RunAndReturn(run func(ctx context.Context, in *storage.ListFilesByHashRequest, opts ...grpc.CallOption) (*storage.ListFilesByHashResponse, error)) *StorageServiceClient_ListFilesByHash_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function for the type StorageServiceClient
func (_mock *StorageServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[storage.UploadFileRequest, storage.UploadFileResponse], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 grpc.ClientStreamingClient[storage.UploadFileRequest, storage.UploadFileResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (grpc.ClientStreamingClient[storage.UploadFileRequest, storage.UploadFileResponse], error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) grpc.ClientStreamingClient[storage.UploadFileRequest, storage.UploadFileResponse]); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ClientStreamingClient[storage.UploadFileRequest, storage.UploadFileResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StorageServiceClient_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type StorageServiceClient_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx
//   - opts
func (_e *StorageServiceClient_Expecter) UploadFile(ctx interface{}, opts ...interface{}) *StorageServiceClient_UploadFile_Call {
	return &StorageServiceClient_UploadFile_Call{Call: _e.mock.On("UploadFile",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *StorageServiceClient_UploadFile_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *StorageServiceClient_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[1].([]grpc.CallOption)
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *StorageServiceClient_UploadFile_Call) Return(clientStreamingClient grpc.ClientStreamingClient[storage.UploadFileRequest, storage.UploadFileResponse], err error) *StorageServiceClient_UploadFile_Call {
	_c.Call.Return(clientStreamingClient, err)
	return _c
}

func (_c *StorageServiceClient_UploadFile_Call) RunAndReturn(run func(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[storage.UploadFileRequest, storage.UploadFileResponse], error)) *StorageServiceClient_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}
