// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"hash"

	mock "github.com/stretchr/testify/mock"
)

// NewHashProvider creates a new instance of HashProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHashProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *HashProvider {
	mock := &HashProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HashProvider is an autogenerated mock type for the HashProvider type
type HashProvider struct {
	mock.Mock
}

type HashProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *HashProvider) EXPECT() *HashProvider_Expecter {
	return &HashProvider_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type HashProvider
func (_mock *HashProvider) Hash() hash.Hash {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 hash.Hash
	if returnFunc, ok := ret.Get(0).(func() hash.Hash); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(hash.Hash)
		}
	}
	return r0
}

// HashProvider_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type HashProvider_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
func (_e *HashProvider_Expecter) Hash() *HashProvider_Hash_Call {
	return &HashProvider_Hash_Call{Call: _e.mock.On("Hash")}
}

func (_c *HashProvider_Hash_Call) Run(run func()) *HashProvider_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HashProvider_Hash_Call) Return(hash1 hash.Hash) *HashProvider_Hash_Call {
	_c.Call.Return(hash1)
	return _c
}

func (_c *HashProvider_Hash_Call) RunAndReturn(run func() hash.Hash) *HashProvider_Hash_Call {
	_c.Call.Return(run)
	return _c
}
